// Every page the app serves, with the h1 each must show: the routes and layout specs walk it
export const ROUTES: { path: string; heading: string | RegExp }[] = [
  { path: "/", heading: "Home overview" },
  { path: "/today", heading: "Today" },
  { path: "/activity-feed", heading: "Activity feed" },
  { path: "/quick-stats", heading: "Quick stats" },
  { path: "/attainment", heading: "Attainment" },
  { path: "/quota-plan", heading: "Quota plan" },
  { path: "/pipeline", heading: "Pipeline board" },
  { path: "/forecast", heading: "Forecast" },
  { path: "/quotes", heading: "Quotes" },
  { path: "/quotes/new", heading: "New quote" },
  { path: "/products", heading: "Products" },
  { path: "/approvals", heading: "Approvals" },
  { path: "/activities", heading: "Activity timeline" },
  { path: "/tasks", heading: "Tasks" },
  { path: "/contacts", heading: "Homeowners" },
  { path: "/contacts/1", heading: "Walter Greaves" },
  { path: "/territories", heading: "Territories" },
  { path: "/reports", heading: "Reports" },
  { path: "/reports/conversion", heading: "Conversion" },
  { path: "/settings", heading: "Settings" },
  { path: "/settings/billing", heading: "Billing" },
  { path: "/settings/team", heading: "Team members" },
  { path: "/settings/integrations", heading: "Integrations" },
  { path: "/account/profile", heading: "Profile" },
  { path: "/account/preferences", heading: "Preferences" },
  { path: "/account/notifications", heading: "Notifications" },
]
